from pathlib import Path
import concurrent.futures
import difflib
import hashlib
import json
import re
import subprocess
import tempfile

ROOT = Path.cwd()
BEFORE = ROOT.parent / 'sindarin-rust-parity-completion/bin/sn'
AFTER = ROOT / 'bin/sn'
BASELINE = '40365381e93f65f5f912bb248f5aa40bd07685ed'


def normalize(s, exit_name):
    s = re.sub(r'extern "C" \{\n    #\[link_name = "fwrite"\].*?(?=#\[cfg\(windows\)\]\nfn __sn_write_windows_text)', '', s, flags=re.S)
    s = re.sub(r'#\[cfg\(windows\)\]\nfn __sn_write_windows_text.*?macro_rules! println \{.*?^\}', 'IO_PLATFORM_HELPERS', s, flags=re.S | re.M)
    for name in ('__sn_write_bytes', '__sn_println_string', '__sn_println_char'):
        s = re.sub(r'fn '+name+r'\([^\n]+\) \{.*?^\}', 'IO_FUNCTION_'+name, s, flags=re.S | re.M)
    s = re.sub(r'fn (\w+)\(message: &\x27static str\) -> ! \{.*?^\}', r'IO_ERROR_HELPER_\1', s, flags=re.S | re.M)
    s = re.sub(r'^    let __sn_stdio_guard\w* = __SnStdioGuard\w*;\n', '', s, flags=re.M)
    s = s.replace('crate::'+exit_name, 'std::process::exit').replace(exit_name+'(', 'std::process::exit(')
    s = re.sub(r'if !__sn_assert_condition\w* \{.*?std::process::exit\(1\); \}', 'IO_ASSERT_FAILURE', s)
    s = re.sub(r'\n{3,}', '\n\n', s)
    return s


def main():
    sources = [ROOT / (s[:-len('.expected.rs')] + '.sn') for s in
               subprocess.check_output(['git', 'ls-tree', '-r', '--name-only', BASELINE, 'tests'], text=True).splitlines()
               if s.endswith('.expected.rs')]
    assert len(sources) == 372
    with tempfile.TemporaryDirectory(prefix='sn-stdio-snapshot-review-') as directory:
        directory = Path(directory)
        def review(item):
            index, source = item
            opt = source.with_suffix('.opt')
            flags = ['-O0'] if not opt.exists() else ([] if opt.read_text().strip() == 'default' else [opt.read_text().strip()])
            texts = []
            for target, compiler in [('before', BEFORE), ('after', AFTER)]:
                destination = directory / (str(index)+target+'.rs')
                result = subprocess.run([str(compiler), str(source.relative_to(ROOT)), '--emit-rust', '--no-install', '-l', '1', *flags, '-o', str(destination)], capture_output=True, timeout=120)
                assert result.returncode == 0, (source, target, result.stderr)
                texts.append(destination.read_text())
            before, after = texts
            oracle = source.with_suffix('.expected.rs')
            old_oracle = subprocess.check_output(['git', 'show', BASELINE+':'+str(oracle.relative_to(ROOT))]).decode()
            assert before == old_oracle, source
            exit_name = re.search(r'fn (\w+)\(status: i32\) -> !', after).group(1)
            old_normal, new_normal = normalize(before, exit_name), normalize(after, exit_name)
            if old_normal != new_normal:
                (ROOT / '.sn/stdio-unclassified.diff').write_text(''.join(difflib.unified_diff(old_normal.splitlines(True), new_normal.splitlines(True))))
                raise AssertionError('Unclassified non-I/O change: '+str(source))
            record = {'source': str(source.relative_to(ROOT)), 'source_sha256': hashlib.sha256(source.read_bytes()).hexdigest(), 'before_sha256': hashlib.sha256(before.encode()).hexdigest(), 'after_sha256': hashlib.sha256(after.encode()).hexdigest(), 'normalized_sha256': hashlib.sha256(old_normal.encode()).hexdigest()}
            return oracle, after, record
        with concurrent.futures.ThreadPoolExecutor(max_workers=8) as pool:
            reviews = list(pool.map(review, enumerate(sources)))
        # No file is refreshed until every current baseline is exact and every
        # normalized before/after source agrees outside the reviewed I/O sites.
        for oracle, after, record in reviews:
            oracle.write_text(after)
        (ROOT / '.sn/stdio-snapshot-review.json').write_text(json.dumps({'scope': '372 exact pre-change generation oracles; changes restricted to global I/O support, generated byte-print helpers, diagnostic paths and main flush/exit handling; source hashes unchanged', 'before_compiler_sha256': hashlib.sha256(BEFORE.read_bytes()).hexdigest(), 'after_compiler_sha256': hashlib.sha256(AFTER.read_bytes()).hexdigest(), 'cases': [r for _, _, r in reviews]}, indent=2)+'\n')
        print('Reviewed all',len(reviews),'snapshots: no changes outside classified I/O sites.')


main()
