#include <assert.h>
#include <string.h>
#include "sn_array.h"
#include "native_byte_array_bridge.h"

static SnArray *original;
static SnAbiValue *alias;
static uint64_t callbacks;
static SnAbiStatus observe(SnAbiValue *view, uintptr_t context)
{
    SnArray *header = NULL;
    assert(context == 42 || context == 99);
    assert(sn_abi_v1_native_byte_array_data(alias ? alias : view, &header) == 0);
    assert(header == original && header->len == 5 + (long long)(callbacks * 2));
    if (context == 99 && !callbacks) sn_abi_v1_release(view);
    callbacks++;
    return sn_test_native_bytes_push(view, 0);
}
int main(void)
{
    SnAbiInfo info;
    const uint64_t masks[] = {7, 31, 63, 127, 255, 511};
    for (uint32_t i = 0; i < 6; i++) {
        assert(sn_abi_v1_query(SN_ABI_V1_VERSION + i, 0, &info, sizeof(info)) == 0);
        assert(info.capabilities == masks[i]);
        SnAbiInfo saved = info;
        assert(sn_abi_v1_query(SN_ABI_V1_VERSION + i, SN_ABI_CAP_NATIVE_BYTE_ARRAYS, &info, sizeof(info)) == SN_ABI_UNSUPPORTED);
        assert(memcmp(&info, &saved, sizeof(info)) == 0);
    }
    assert(sn_abi_v1_query(SN_ABI_V1_6_VERSION, SN_ABI_CAP_NATIVE_BYTE_ARRAYS, &info, sizeof(info)) == 0 && info.capabilities == 1023);
    SnAbiInfo saved = info;
    assert(sn_abi_v1_query(SN_ABI_V1_7_VERSION + 1, 0, &info, sizeof(info)) == SN_ABI_VERSION_MISMATCH);
    assert(memcmp(&info, &saved, sizeof(info)) == 0);
    SnAbiValue *view = NULL, *copy = NULL, *wrong = NULL, *out = (SnAbiValue *)(uintptr_t)1;
    SnArray *header = (SnArray *)(uintptr_t)1;
    SnAbiBytes bytes = {(const uint8_t *)(uintptr_t)1, 42};
    assert(sn_abi_v1_native_byte_array_borrow(NULL, &out) == 0 && !out);
    assert(sn_abi_v1_native_byte_array_adopt(NULL, &out) == 0 && !out);
    assert(sn_abi_v1_native_byte_array_copy(NULL, &out) == 0 && !out);
    assert(sn_abi_v1_native_byte_array_copy_bytes(NULL, 0, &out) == 0 && !out);
    assert(sn_abi_v1_native_byte_array_data(NULL, &header) == 0 && !header);
    assert(sn_abi_v1_native_byte_array_bytes(NULL, &bytes) == 0 && !bytes.data && !bytes.length);
    assert(sn_abi_v1_native_byte_array_data(NULL, NULL) == SN_ABI_INVALID_ARGUMENT);
    assert(sn_abi_v1_native_byte_array_bytes(NULL, NULL) == SN_ABI_INVALID_ARGUMENT);
    assert(sn_abi_v1_native_byte_array_copy(NULL, NULL) == SN_ABI_INVALID_ARGUMENT);
    original = sn_test_native_bytes_new();
    out = (SnAbiValue *)(uintptr_t)1;
    assert(sn_abi_v1_native_byte_array_adopt(original, NULL) == SN_ABI_INVALID_ARGUMENT);
    assert(sn_abi_v1_native_byte_array_borrow(original, NULL) == SN_ABI_INVALID_ARGUMENT);
    original->elem_size = 8;
    assert(sn_abi_v1_native_byte_array_adopt(original, &out) == SN_ABI_WRONG_KIND && out == (SnAbiValue *)(uintptr_t)1);
    original->elem_size = 1;
    original->elem_tag = SN_TAG_BOOL;
    assert(sn_abi_v1_native_byte_array_borrow(original, &out) == SN_ABI_WRONG_KIND && out == (SnAbiValue *)(uintptr_t)1);
    original->elem_tag = SN_TAG_DEFAULT;
    assert(sn_abi_v1_native_byte_array_borrow(original, &out) == SN_ABI_WRONG_KIND);
    original->elem_tag = SN_TAG_BYTE;
    long long capacity = original->cap;
    original->cap = 1;
    assert(sn_abi_v1_native_byte_array_adopt(original, &out) == SN_ABI_INVALID_ARGUMENT && out == (SnAbiValue *)(uintptr_t)1);
    original->cap = capacity;
    original->len = -1;
    assert(sn_abi_v1_native_byte_array_borrow(original, &out) == SN_ABI_INVALID_ARGUMENT);
    original->len = 4;
    void *data = original->data;
    original->data = NULL;
    assert(sn_abi_v1_native_byte_array_borrow(original, &out) == SN_ABI_INVALID_ARGUMENT);
    original->data = data;
    assert(sn_abi_v1_native_byte_array_borrow(original, &view) == 0);
    alias = sn_abi_v1_retain(view);
    assert(sn_abi_v1_native_byte_array_data(alias, &header) == 0 && header == original);
    assert(sn_abi_v1_native_byte_array_copy(view, &copy) == 0);
    assert(sn_abi_v1_native_byte_array_bytes(copy, &bytes) == 0 && bytes.length == 4 && memcmp(bytes.data, "\0\177\200\377", 4) == 0);
    assert(sn_abi_v1_native_byte_array_data(copy, &header) == 0 && header != original);
    assert(header->elem_copy == original->elem_copy && header->elem_release == original->elem_release);
    original->elem_tag = SN_TAG_CHAR;
    header = (SnArray *)(uintptr_t)1;
    bytes = (SnAbiBytes){(const uint8_t *)(uintptr_t)1, 42};
    assert(sn_abi_v1_native_byte_array_data(view, &header) == SN_ABI_WRONG_KIND && header == (SnArray *)(uintptr_t)1);
    assert(sn_abi_v1_native_byte_array_copy(view, &out) == SN_ABI_WRONG_KIND && out == (SnAbiValue *)(uintptr_t)1);
    assert(sn_abi_v1_native_byte_array_bytes(view, &bytes) == SN_ABI_WRONG_KIND && bytes.length == 42 && bytes.data == (const uint8_t *)(uintptr_t)1);
    original->elem_tag = SN_TAG_BYTE;
    assert(sn_test_native_bytes_reenter(view, observe, 42) == 0 && callbacks == 64);
    assert(original->len == 132);
    assert(sn_abi_v1_native_byte_array_bytes(alias, &bytes) == 0 && bytes.data == original->data && bytes.length == 132);
    assert(sn_abi_v1_buffer_copy((const uint8_t *)"x", 1, &wrong) == 0);
    assert(sn_abi_v1_native_byte_array_copy(wrong, &out) == SN_ABI_WRONG_KIND);
    assert(sn_abi_v1_native_byte_array_data(wrong, &header) == SN_ABI_WRONG_KIND);
    sn_abi_v1_release(wrong);
    assert(sn_abi_v1_array_new(1, &wrong) == 0);
    assert(sn_abi_v1_native_byte_array_copy(wrong, &out) == SN_ABI_WRONG_KIND);
    sn_abi_v1_release(wrong);
    assert(sn_abi_v1_string_copy("x", &wrong) == 0);
    assert(sn_abi_v1_native_byte_array_bytes(wrong, &bytes) == SN_ABI_WRONG_KIND);
    sn_abi_v1_release(wrong);
    SnArray empty = {NULL, 0, 0, sizeof(uint8_t), NULL, NULL, SN_TAG_DEFAULT};
    assert(sn_abi_v1_native_string_array_borrow(sn_array_new(sizeof(char *), 0), &wrong) == 0);
    /* The borrowed string header is owned explicitly, never by its view. */
    SnArray *string_header = NULL;
    assert(sn_abi_v1_native_string_array_data(wrong, &string_header) == 0);
    assert(sn_abi_v1_native_byte_array_copy(wrong, &out) == SN_ABI_WRONG_KIND);
    sn_abi_v1_release(wrong); sn_array_free(string_header);
    sn_abi_v1_release(view); sn_abi_v1_release(alias); alias = NULL;
    assert(sn_test_native_bytes_destroyed() == 0);
    sn_test_native_bytes_free(original);
    assert(sn_test_native_bytes_destroyed() == 132);
    sn_abi_v1_release(copy);
    assert(sn_test_native_bytes_destroyed() == 136);
    callbacks = 0;
    original = sn_test_native_bytes_new();
    assert(sn_abi_v1_native_byte_array_adopt(original, &view) == 0);
    assert(sn_test_native_bytes_reenter(view, observe, 99) == 0 && callbacks == 64);
    assert(sn_test_native_bytes_destroyed() == 268);
    original = sn_test_native_bytes_new();
    assert(sn_abi_v1_native_byte_array_adopt(original, &view) == 0);
    sn_test_native_bytes_copy_consume(view);
    assert(sn_abi_v1_native_byte_array_copy(view, &copy) == 0);
    assert(sn_test_native_bytes_destroyed() == 272);
    assert(sn_abi_v1_native_byte_array_bytes(copy, &bytes) == 0 && bytes.length == 4 && !memcmp(bytes.data, "\0\177\200\377", 4));
    sn_abi_v1_release(copy);
    assert(sn_test_native_bytes_destroyed() == 276);
    assert(sn_abi_v1_native_byte_array_borrow(&empty, &view) == 0);
    assert(sn_abi_v1_native_byte_array_copy(view, &copy) == 0);
    assert(sn_abi_v1_native_byte_array_data(copy, &header) == 0 && header != &empty && header->len == 0);
    sn_abi_v1_release(view); sn_abi_v1_release(copy);
    const uint8_t raw[] = {0, 255, 128};
    assert(sn_abi_v1_native_byte_array_copy_bytes(raw, sizeof(raw), &view) == 0);
    assert(sn_abi_v1_native_byte_array_bytes(view, &bytes) == 0 && bytes.data != raw && bytes.length == sizeof(raw) && !memcmp(bytes.data, raw, sizeof(raw)));
    sn_abi_v1_release(view);
    assert(sn_abi_v1_native_byte_array_copy_bytes(raw, 0, &view) == 0 && view);
    assert(sn_abi_v1_native_byte_array_bytes(view, &bytes) == 0 && !bytes.length);
    sn_abi_v1_release(view);
    assert(sn_abi_v1_native_byte_array_copy_bytes(NULL, 1, &out) == SN_ABI_INVALID_ARGUMENT && out == (SnAbiValue *)(uintptr_t)1);
    assert(sn_abi_v1_native_byte_array_copy_bytes(raw, UINT64_MAX, &out) == SN_ABI_OUT_OF_RANGE && out == (SnAbiValue *)(uintptr_t)1);
    assert(sn_abi_v1_native_byte_array_copy_bytes(raw, 1, NULL) == SN_ABI_INVALID_ARGUMENT);
    assert(sn_abi_v1_native_byte_array_take(NULL, &header) == SN_ABI_INVALID_ARGUMENT);
    assert(sn_abi_v1_native_byte_array_take(&view, NULL) == SN_ABI_INVALID_ARGUMENT);
    view = NULL;
    assert(sn_abi_v1_native_byte_array_take(&view, &header) == 0 && !header && !view);
    assert(sn_abi_v1_native_byte_array_borrow(&empty, &view) == 0);
    header = (SnArray *)(uintptr_t)1;
    SnAbiValue *saved_view = view;
    assert(sn_abi_v1_native_byte_array_take(&view, &header) == SN_ABI_INVALID_ARGUMENT && view == saved_view && header == (SnArray *)(uintptr_t)1);
    sn_abi_v1_release(view);
    original = sn_test_native_bytes_new();
    assert(sn_abi_v1_native_byte_array_adopt(original, &view) == 0);
    alias = sn_abi_v1_retain(view);
    assert(sn_abi_v1_native_byte_array_take(&view, &header) == SN_ABI_INVALID_ARGUMENT && view == alias && header == (SnArray *)(uintptr_t)1);
    sn_abi_v1_release(alias); alias = NULL;
    assert(sn_abi_v1_native_byte_array_take(&view, &header) == 0 && !view && header == original);
    assert(sn_test_native_bytes_destroyed() == 276 && header->elem_copy && header->elem_release);
    sn_test_native_bytes_free(header);
    assert(sn_test_native_bytes_destroyed() == 280);
    assert(sn_abi_v1_buffer_copy(raw, sizeof(raw), &view) == 0);
    saved_view = view; header = (SnArray *)(uintptr_t)1;
    assert(sn_abi_v1_native_byte_array_take(&view, &header) == SN_ABI_WRONG_KIND && view == saved_view && header == (SnArray *)(uintptr_t)1);
    sn_abi_v1_release(view);
    puts("native byte array views: pass");
    return 0;
}
